In [1]:
import numpy as np
np.__version__

'1.19.2'

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
b= np.linspace(1,5,5)
print(b)


array([1., 2., 3., 4., 5.])

In [5]:
c= np.ones((2, 4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
d = np.eye(7)
print(d)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [7]:
e = np.diag([1,2,3,4])
print(e)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [8]:
f = np.random.rand(4)
print(f)

[0.13376711 0.03021976 0.58045527 0.90040795]


In [9]:
g = np.array([1,2,3,4,5])
print(g)

[1 2 3 4 5]


In [11]:
h= np.array({"Ayesha"})
print(h)
print(type(h))


{'Ayesha'}
<class 'numpy.ndarray'>


In [12]:
list= [1,2,3,4,5,6],[1,2,3,4,5,6]
i=np.array((list))
i

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [13]:
j = np.arange(15).reshape(3, 5)
j

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
np.empty((2, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
from numpy import pi

np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
k = np.linspace(0, 2*pi, 100)
k

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [19]:
l = np.sin(5)
l

-0.9589242746631385

In [20]:
np.empty_like((4, 6))

array([         0, 1075052544])

In [21]:

m = np.random.randint(50,size=6)
m

array([ 0, 27,  4, 32, 21, 30])

In [22]:
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws > 0,1,-1)
walk = steps.cumsum()

walk


array([ -1,   0,  -1,   0,   1,   2,   3,   2,   3,   2,   3,   4,   5,
         4,   3,   2,   1,   2,   3,   4,   3,   2,   3,   2,   1,   0,
        -1,  -2,  -3,  -2,  -1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -5,
        -4,  -3,  -2,  -1,   0,  -1,   0,  -1,   0,   1,   2,   3,   2,
         3,   4,   3,   4,   3,   2,   3,   4,   3,   4,   3,   2,   1,
         0,  -1,   0,   1,   2,   3,   4,   3,   2,   1,   2,   3,   4,
         3,   2,   1,   0,  -1,  -2,  -1,   0,  -1,  -2,  -3,  -2,  -3,
        -2,  -3,  -4,  -3,  -4,  -3,  -4,  -5,  -6,  -5,  -6,  -5,  -4,
        -5,  -4,  -5,  -4,  -5,  -6,  -5,  -4,  -3,  -4,  -3,  -2,  -3,
        -4,  -5,  -6,  -5,  -4,  -5,  -4,  -5,  -4,  -3,  -4,  -5,  -4,
        -5,  -4,  -5,  -4,  -3,  -4,  -3,  -4,  -5,  -6,  -5,  -6,  -7,
        -6,  -7,  -8,  -9,  -8,  -7,  -8,  -7,  -6,  -5,  -4,  -3,  -4,
        -3,  -4,  -3,  -4,  -5,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11,
       -10, -11, -12, -11, -12, -11, -12, -13, -12, -11, -10,  -

In [23]:
array4 = np.array([1, 2, 3, 4, 5])
array4.dtype

dtype('int32')

In [24]:
rg = np.random.default_rng(1)

a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [25]:
b += a

b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [26]:
b = np.linspace(0, pi, 3)

b.dtype.name


'float64'

In [28]:
c = a+b

c

array([[3.        , 4.57079633, 6.14159265],
       [3.        , 4.57079633, 6.14159265]])

In [29]:
d = np.exp(c*1j)

d

array([[-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j],
       [-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j]])

In [30]:
d.dtype.name

'complex128'

In [31]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [32]:
a.sum()

3.1057109529998157

In [34]:
a.min()


0.027559113243068367

In [35]:
a.max()


0.8277025938204418

In [36]:
arry2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arry2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
print(arry2d[0][2])


3


In [41]:
arry3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arry3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arry3d.shape


(2, 2, 3)

In [43]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

arr


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
a = np.array([1, 2, 3, 4, 5, 6])
x = a.copy()
a[0] = 42

print(a)
print(x)

[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [45]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)

print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
a = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

for x in np.nditer(a):
    print(x)

1
2
3
4
5
6
7
8


In [47]:
a1 = np.array(["My name"])
a2 = np.array(["is :"])

b = np.concatenate((a1, a2))
print(b)

['My name' 'is :']


In [49]:
a = np.array([20, 21, 22, 23])
b = [True, False, True, False]

x = a[b]
print(x)

[20 22]


In [50]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')